// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations/push (bypasses PgBouncer)
    // Runtime Prisma Client will use DATABASE_URL (with PgBouncer)
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
